apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service-canary
spec:
  selector:
    app: {{ .Release.Name }}-app-canary
  ports:
    - name: app-port-canary
      protocol: TCP
      port: 5003
      targetPort: 5003
  type: NodePort